name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Reformat
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Check Go Version (Why not!)
        run: go version
      
      - name: Tests job
        run: go test -z $(go fmt ./...)
